version: '3'
services:
  web:
    build: .
    command: python -u app.py
    volumes:
      - '.:/code'
    ports:
     - "5000:5000"
    links:
      - db
  db:
    image: mongo:3.0.2
  yarn-cache:
    image: busybox
    volumes:
      - /root/.yarn-cache